[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  framework = "#static"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
