[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  framework = "#static"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
